[package]
name = "vending-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_float_eq = "1.1.3"
serde = "1.0.163"
time = { version = "0.3.21", features = ["macros","serde"] }
